export const API_BASE_URL = 'http://localhost:8080';

export const USER_TYPES = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  DELIVERY_PERSON: 'DELIVERY_PERSON'
};

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ASSIGNED: 'ASSIGNED',
  PICKUP: 'PICKUP',
  TRANSIT: 'TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};